# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.srcs/sources_1/bd/PS/ip/PS_axi_smc_0/PS_axi_smc_0.xci
# IP: The module: 'PS_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/bd_d07b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_0/bd_d07b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_1/bd_d07b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_2/bd_d07b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_3/bd_d07b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_4/bd_d07b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_5/bd_d07b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_6/bd_d07b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_7/bd_d07b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_8/bd_d07b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_9/bd_d07b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_10/bd_d07b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_11/bd_d07b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_12/bd_d07b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_1/bd_d07b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_1/bd_d07b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_5/bd_d07b_s00a2s_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_6/bd_d07b_sarn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_7/bd_d07b_srn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_8/bd_d07b_sawn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_9/bd_d07b_swn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_10/bd_d07b_sbn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_11/bd_d07b_m00s2a_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.srcs/sources_1/bd/PS/ip/PS_axi_smc_0/PS_axi_smc_0.xci
# IP: The module: 'PS_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/bd_d07b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_0/bd_d07b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_1/bd_d07b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_2/bd_d07b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_3/bd_d07b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_4/bd_d07b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_5/bd_d07b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_6/bd_d07b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_7/bd_d07b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_8/bd_d07b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_9/bd_d07b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_10/bd_d07b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_11/bd_d07b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_12/bd_d07b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_1/bd_d07b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_1/bd_d07b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_5/bd_d07b_s00a2s_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_6/bd_d07b_sarn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_7/bd_d07b_srn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_8/bd_d07b_sawn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_9/bd_d07b_swn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_10/bd_d07b_sbn_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/bd_0/ip/ip_11/bd_d07b_m00s2a_0_ooc.xdc

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/ip/PS_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
