# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PS/PS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS || ORIG_REF_NAME==PS} -quiet] -quiet

# IP: bd/PS/ip/PS_processing_system7_0_0/PS_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_processing_system7_0_0 || ORIG_REF_NAME==PS_processing_system7_0_0} -quiet] -quiet

# IP: bd/PS/ip/PS_axi_bram_ctrl_0_0/PS_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_axi_bram_ctrl_0_0 || ORIG_REF_NAME==PS_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/PS/ip/PS_blk_mem_gen_0_0/PS_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_blk_mem_gen_0_0 || ORIG_REF_NAME==PS_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/PS/ip/PS_axi_smc_0/PS_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_axi_smc_0 || ORIG_REF_NAME==PS_axi_smc_0} -quiet] -quiet

# IP: bd/PS/ip/PS_rst_ps7_0_50M_0/PS_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_rst_ps7_0_50M_0 || ORIG_REF_NAME==PS_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Github/FPGA-Elec-Design/Xilinx_Proj/PS/PS.gen/sources_1/bd/PS/PS_ooc.xdc
